name: atlas-ingest
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1c
  - pip=19.2.2
  - python=3.6.9
  - readline=7.0
  - setuptools=41.0.1
  - sqlite=3.29.0
  - tk=8.6.8
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - cachetools==3.1.1
    - chardet==3.0.4
    - google-api-python-client==1.7.10
    - google-auth==1.6.3
    - google-auth-httplib2==0.0.3
    - gspread==3.1.0
    - gspread-dataframe==3.0.2
    - httplib2==0.13.0
    - idna==2.8
    - mysql-connector==2.2.9
    - numpy==1.16.4
    - oauth2client==4.1.3
    - pandas==0.24.2
    - psycopg2==2.8.3
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.5
    - python-dateutil==2.8.0
    - pytz==2019.1
    - requests==2.22.0
    - rsa==4.0
    - six==1.12.0
    - style==1.1.0
    - tqdm==4.32.2
    - update==0.0.1
    - uritemplate==3.0.0
    - urllib3==1.25.3