name: atlas-ingest
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - libffi
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - wheel
  - pip:
    - cachetools
    - chardet
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - gspread
    - gspread-dataframe
    - mysql-connector
    - oauth2client
    - pandas
    - psycopg[binary]
    - pyasn1
    - pyasn1-modules
    - python-dateutil
    - requests
    - tqdm
